export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"

export const MOVIE_DETAILS_REQ = 'FETCH_MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCC = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'FETCH_MOVIE_DETAILS_FAILURE';