export const MOVIE_DETAILS_REQ = 'FETCH_MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCC = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'FETCH_MOVIE_DETAILS_FAILURE';
export const UPDATE_USER_MOVIE_DATA = 'UPDATE_USER_MOVIE_DATA';
