//movie list action types for HomePage
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_NOW_PLAYING_MOVIES = "GET_NOW_PLAYING_MOVIES";
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_ACTION_MOVIES = "GET_ACTION_MOVIES";
export const GET_COMEDY_MOVIES = "GET_COMEDY_MOVIES";
export const GET_CRIME_MOVIES = "GET_CRIME_MOVIES";
export const GET_HORROR_MOVIES = "GET_HORROR_MOVIES";
export const GET_THRILLER_MOVIES = "GET_THRILLER_MOVIES";